spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 3
        page-parameter: pageNumber
        size-parameter: pageSize
      sort:
        sort-parameter: orderBy